# Synthetic QA Generation Configuration

# Global settings
global:
  max_chunk_size: 4000
  min_chunk_size: 1000
  overlap_size: 200

# Factual accuracy mode
factual_mode: true

# Processing settings for specific file types
processing:
  html_pages:
    full_document_threshold: 20000
    comprehensive_questions: true
  
  faq:
    enabled: true
    generate_rephrased_questions: true
    generate_related_questions: true
    max_rephrased_questions: 7
    max_related_questions: 3
    context_size: 3

# Iterations by document type
iterations:
  regular_document: 1
  faq_document: 1

# Question generation style variations
question_styles:
  writing_styles:
    - name: 'Formal'
      description: 'Write the question in a formal, academic tone. As a student would write formally (but not too complicated)'
    - name: 'Casual'
      description: 'Rewrite the question in a natural, simple-worded, conversational tone—clear and approachable brazilian student. Avoid formal complex phrasing, but also do not use slang or excessively casual language.'
    - name: 'Direct'
      description: 'Write a direct, search-like simple query/keywords-based lazy but understandable question (no question mark) seeking specific information.'
    - name: 'Confused_Indirect'
      description: 'Write the question as a student who is hesitant, using unsure terms to phrase the question (but not too wordy or insecure), indicating uncertainty about the process (not about himself).'
    - name: 'Incorrect Premise'
      description: "Question stems from a factually incorrect/WRONG premise or a common misunderstanding from a student. The user's query should implicitly treat this incorrect information as true, naturally prompting a corrective response from the assistant."


  question_types:
    - name: 'Informational'
      description: 'Seek factual information. The "What".'
    - name: 'Procedural'
      description: 'Ask about processes, steps, or how to do things. The "How"'
    - name: 'Conceptual'
      description: 'Seek explanation or understanding of concepts or policies. The "Why"'

# API providers configuration
providers:
  faq_extraction:
    provider: genai
    model: gemini-2.0-flash
    temperature: 0.4
    max_tokens: 8192

  styled_question:
    provider: genai # openai
    model: gemini-2.0-flash
    rate_limit_rpm: 14
    temperature: 0.4
    max_tokens: 8192

  related_question:
    provider: genai # openai
    model: gemini-2.0-flash
    rate_limit_rpm: 14
    temperature: 0.4
    max_tokens: 8192

  rephrased_question:
    provider: genai # openai
    model: gemini-2.0-flash
    rate_limit_rpm: 14
    temperature: 0.4
    max_tokens: 8192
  
  answer:
    provider: genai
    model: gemini-2.0-flash
    rate_limit_rpm: 14
    temperature: 0.5
    max_tokens: 8192

# File processing settings
file_processing:
  include_extensions:
    - .html
    - .htm
    - .pdf
    - .txt
    - .md
  
  exclude_patterns:
    - images/
    - assets/
    - .git/
    - styles/
    - js/

# Output settings
output:
  save_debug: true
  format: json
  include_source: true
