# Synthetic QA Generation Configuration

# Global settings
global:
  max_chunk_size: 4000
  min_chunk_size: 1000
  overlap_size: 200
  logging_level: DEBUG

# Processing settings for specific file types
processing:
  faq:
    enabled: true
    generate_rephrased_questions: true
    generate_related_questions: true
    max_rephrased_questions: 7
    max_related_questions: 3
    context_size: 3
    batch_size: 10

  raft:
    num_distractors: 4
    p_golden_include: 0.8



# Iterations by document type (not used)
iterations:
  regular_document: 1
  faq_document: 1
  component_document: 1

# Question generation style variations
question_styles:
  writing_styles:
    - name: 'Formal'
      goal: 'Ensure the Final LLM handles polite, grammatically correct, as a student would write it.'
      description: 'Generate a polite question using grammatically correct, complete sentences and a slightly formal tone. Represent a student interacting respectfully and formally, but avoid overly complex, archaic language or being prolix.'
      iterations: 2

    - name: 'Casual'
      goal: 'Simulate common, less formal but still complete-sentence interactions; improve robustness to everyday language.'
      description: 'Generate a question using natural, conversational, simpler Portuguese, as a Brazilian student might ask directly in a chat. Use complete sentences but avoid complex phrasing. **Crucial: Maintain clear grammar and politeness; do NOT use slang, abbreviations, or excessive informality.** Example: "Como faço pra trancar?" instead of "Qual o procedimento para trancamento?".'
      iterations: 2

    - name: 'Naturalistic/Imperfect'
      goal: 'Capture realistic, quickly typed/spoken inputs that use full sentences but contain common grammatical errors, unconventional word order, or minor typos, without losing the core meaning. Improve robustness to non-standard but understandable inputs.'
      description: 'Generate a question as a student might type quickly into a chat. Use full sentences but **intentionally introduce common, realistic grammatical errors (e.g., verb conjugation, concordance), slightly unconventional word order, or minor typos.** The core meaning and intent **must remain clear and easily understandable**, but the sentence structure should not be perfectly polished. Avoid slang or keyword-only fragments. Examples: "como faz pra trancar a materia", "se eu reprovar no verao conta pro desligamento?", "qual o prazo minimo engenharia da computacao pra formar?".'
      iterations: 2


  question_types:
    - name: 'Informational'
      description: 'Seek factual information. The "What".'
    - name: 'Procedural'
      description: 'Ask about processes, steps, or how to do things. The "How"'
    - name: 'Conceptual'
      description: 'Seek explanation or understanding of concepts or policies. The "Why"'

# API providers configuration
providers:
  faq_extraction:
    provider: genai
    model: gemini-2.5-flash-preview-05-20
    temperature: 0.4
    thinking_budget: 8000
    max_tokens: 65000

  offerings_extraction:
    provider: genai
    model: gemini-2.5-flash-preview-05-20
    temperature: 0.4
    thinking_budget: 8000
    max_tokens: 65000

  default_question:
    provider: genai
    model: gemini-2.5-flash-preview-05-20
    rate_limit_rpm: 4
    temperature: 0.4
    max_tokens: 16384
    thinking_budget: 8000

  default_answer:
    provider: genai
    model: gemini-2.5-flash-preview-05-20
    rate_limit_rpm: 4
    temperature: 0.4
    max_tokens: 16384
    thinking_budget: 8000

  styled_question:
    provider: genai
    model: gemini-2.5-flash-preview-05-20
    rate_limit_rpm: 10
    temperature: 0.4
    max_tokens: 2048

  cot_answer:
    provider: genai
    model: gemini-2.5-flash-preview-05-20
    rate_limit_rpm: 10
    temperature: 0.4
    max_tokens: 8192
    thinking_budget: 2048

  related_question:
    provider: genai # openai
    model: gemini-2.5-flash-preview-05-20
    rate_limit_rpm: 14
    temperature: 0.4
    max_tokens: 8192

  rephrased_question:
    provider: genai # openai
    model: gemini-2.5-flash-preview-05-20
    rate_limit_rpm: 14
    temperature: 0.4
    max_tokens: 8192
  
  answer:
    provider: genai
    model: gemini-2.5-flash-preview-05-20
    rate_limit_rpm: 14
    temperature: 0.5
    max_tokens: 8192
  
  component_text_extraction:
    provider: genai
    model: gemini-2.5-flash-preview-05-20
    rate_limit_rpm: 4
    temperature: 0.3
    max_tokens: 65000

  text_extraction:
    provider: genai
    model: gemini-2.5-flash-preview-05-20
    rate_limit_rpm: 4
    temperature: 0.3
    max_tokens: 65000
    thinking_budget: 8000

  text_chunking:
    provider: genai
    model: gemini-2.5-flash-preview-05-20
    rate_limit_rpm: 4
    temperature: 0.2
    max_chunking_length: 40000
    max_tokens: 65000
    thinking_budget: 12000

# File processing settings
file_processing:
  include_extensions:
    - .html
    - .htm
    - .pdf
    - .txt
    - .md
  
  ignore:
    - www.cic.unb.br/informacoes/Listas_de_Meno_Honrosa_-_CICDF2024_-.pdf
    - www.cic.unb.br/informacoes/Plano_de_Contingencia_do_Instituto_de_Ciencia_exatas.pdf
    - www.cic.unb.br/informacoes/RELATRIO_FINAL_DE_ESTGIO_DAS_LICENCIATURAS.pdf
    - www.cic.unb.br/informacoes/tipograma_CIC.pdf
    - www.cic.unb.br/informacoes/GER_Exposicao_de_motivos.pdf
    - www.cic.unb.br/informacoes/marca-cic.html
    - www.cic.unb.br/informacoes/Manual_Identidade_Visual_UnB.pdf
    - www.cic.unb.br/informacoes/guia_pratico.pdf
    - www.cic.unb.br/informacoes/noticias*
    - www.cic.unb.br/informacoes/noticias/*
    - www.cic.unb.br/ec.html
    - www.cic.unb.br/bcc.html
    - www.cic.unb.br/em.html
    - unb.br/mapas_da_unb_2_2024.pdf
    - unb.br/opine-sobre-o-portal.html
    - unb.br/index.html
    - unb.br/fontes-para-imprensa.html
  
  exclude_patterns:
    - images/
    - assets/
    - .git/
    - styles/
    - js/
  componentes_folder_name: componentes_curriculares
  offerings_folder_name: turmas

# Output settings
output:
  save_debug: true
  format: json
  include_source: true


base_dir: /home/farias/tcc/input/  # set by synthetic_qa_generator
